[package]
name = "kernel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bit_field = "0.10.2"
linked_list_allocator = "0.10.5"
log = "0.4.21"
spin = "0.9.8"
uefi = "0.28.0"
