[toolchain]
# https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
# channel = "nightly-2022-06-30"
channel = "nightly-2024-05-24"
components = [ "rustfmt", "rust-src" ]
targets = [ "x86_64-unknown-linux-gnu" ]

